### PR TITLE
05 -- Shavers of the Lost Yak

### PR DESCRIPTION
**Pull request by kellymurray**
## Rituals (~1h 15m)
- **Standup Meeting** (~15m) -- _Change Seats!_
- **Retrospective** (~30m)
- **Homework Review** (~30m)
- **Three Little Things** (~30m)
- [**Rear View Mirror**](https://github.com/TIY-Durham/2015-FALL-FEE/wiki/Parking-Lot) (~15m)
- **Parking Lot** (~1hr)
- **Short Lecture** (~30m)
### Monday Review -- On Tuesday!
- The Wonderful World of JavaScript
- Git, GitHub, and CLI
- All About Functions
- Control Flow
### Data Types: Lists and Dictionaries
- What are the 4 primitive types in JavaScript?
- What if I need to store more than one value?
- What is a list? How do I make one?
- What is a dictionary? How do I make one?
- How do I get values out?
- How do I put new values in?
- What can I put in a list or dictionary?
- What are they good for?

### CODE REVIEW

**Comment by al-the-x** [comment]
### Blockers
- Why U late to standup, @ericquayson? (Even when standup late...)
- What happens to your code if you die... during the cohort?
- No matter how far down the wrong road you go...
- Google doesn't help for code. WHY GOOGLE WHY?!
- Generating sequences of numbers for "Fibonacci" and "3s and 5s"
- Setting up new katas HARD.
- Arrays and loops also HARD.
- Do U even mocha-chai?
- ZOMG `git push` WHY?
- These appear to be getting harder...
- Merge conflicts?
- Fibonacci == Infinity
- Baby steps seem harder than just solving the problem.
- Pair programming...

**Comment by al-the-x** [comment]
### Volunteers
- Shay Hall (@ShayHall)
- Camille Mauban (@cmauban)
- Jonathan Creasman (@jmcreasman)
- Karlo Eleuterio (@karjac14)
- Eric (@ericquayson)
- Kristine Erickson (@ericksonk)
- Terry Calhoun (@drumslayert)
- Jasmine Baik (@boshnivolo)
- J.R. Worley (@jeffworley)
- David White (@s4dmw)
- Lacey Rice (@Ricecoder)
- Nicky Cadavillo (@nickycadavillo)
- Matt Oliverio (@ironyarder77)
- Emily Pakes (@pakesybot)
- Jeremy Rist (@jeremyrist)
- Rosa Lopez Sanchez (@rosalsm)

**Comment by kellymurray** [comment]
### Three Little Things
- Katas (Fibonacci & 3s and 5s)
- Git CLI, in particular `push` and `merge`
- Setting up tests (Mocha and Chai)

**Comment by kellymurray** [comment]
Accidentally closed it...but it's open again!

**Comment by al-the-x** [comment]
| you | them |
| --- | --- |
| David White | J.R. Worley |
| Terry Calhoun | David White |
| Kristine Erickson | Shay Hall |
| Karlo Eleuterio | Eric |
| Shay Hall | Terry Calhoun |
| Camille Mauban | Emily Pakes |
| Lacey Rice | Rosa Lopez Sanchez |
| Jasmine Baik | Kristine Erickson |
| Eric | Jasmine Baik |
| Jonathan Creasman | Lacey Rice |
| Matt Oliverio | Karlo Eleuterio |
| J.R. Worley | Jonathan Creasman |
| Jeremy Rist | Camille Mauban |
| Rosa Lopez Sanchez | Jeremy Rist |
| Nicky Cadavillo | Matt Oliverio |
| Emily Pakes | Nicky Cadavillo |

**Pull request merged**
